version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: install dependencies
          command: | 
            echo 'true'
            echo $MY_ENV_VAR

workflows:
  newprojects:
    jobs:
      - lint
